### ISSUE TITLE
Not working on Angular 9

### ISSUE THREAD

**Issue by abenmariem** [hivivo/ngx-json-viewer#33]
./node_modules/ngx-json-viewer/__ivy_ngcc__/ngx-json-viewer.es5.js
Module build failed: Error: ENOENT: no such file or directory, open 'd:\dev\angular9\Proje t\node_modules\ngx-json-viewer\__ivy_ngcc__\ngx-json-viewer.es5.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Storage.provideSync (d:\dev\angular9\Processus\processus-eer-clipro-front\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync (d:\dev\angular9\project\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:289:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (d:\dev\angular9\project\node_modules\@ngtools\webpack\src\webpack-input-host.js:35:51)
    at Observable._trySubscribe (d:\dev\angular9\Processus\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (d:\dev\angular9\project\node_modules\rxjs\internal\Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (d:\dev\angular9\project\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:22:20)
    at SyncDelegateHost.read (d:\dev\angular9\project\node_modules\@angular-devkit\core\src\virtual-fs\host\sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (d:\dev\angular9\project\node_modules\@ngtools\webpack\src\compiler_host.js:165:44)
    at VirtualFileSystemDecorator.readFile (d:\dev\angular9\project\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:42:54)
    at processResource (d:\dev\angular9\project\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (d:\dev\angular9\project\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (d:\dev\angular9\project\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (d:\dev\angular9\project\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (d:\dev\angular9\project\node_modules\webpack\lib\NormalModule.js:446:15)

**Comment by arcovoltaico** [comment]
how it was solved? after updating from 2 to 3, I'm getting this error as well. I'm using angular 9.1.13
