### ISSUE TITLE
Publish an Ivy Distribution

### ISSUE THREAD

**Issue by i-singhprince** [hivivo/ngx-json-viewer#72]

**Comment by alfaproject** [comment]
I'd love an Angular 13 version as well

**Comment by micahstubbs** [comment]
I'm go to give this a try. I'll share some notes here as I go.

**Comment by micahstubbs** [comment]
```
npx @angular/cli@12 update @angular/core@12 --force

Package "ng-packagr" has an incompatible peer dependency to "typescript" (requires ">=4.0 <4.2", would install "4.3.5").
```

**Comment by micahstubbs** [comment]
let's manually set `"ng-packagr": "^13.3.0",` in `package.json` and then try:

```bash
npx @angular/cli@13 update @angular/core@13 --force
```

**Comment by micahstubbs** [comment]
let's try `yarn add --dev @angular-devkit/core` to fix the last issue

**Comment by micahstubbs** [comment]
now we see:

```bash
npx @angular/cli@13 update @angular/core@13 --force

# Using package manager: 'yarn'
# Collecting installed dependencies...
# Found 10 dependencies.
# Fetching dependency metadata from registry...
# Package '@angular/core' is already up to date.
```

**Comment by micahstubbs** [comment]
Let's see what happens when we try to build:

```bash
yarn build
yarn run v1.22.18
$ ng-packagr -p package.json
Building Angular Package
(node:99189) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/m/workspace/ngx-json-viewer/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
WARNING: Found configuration in ngx-json-viewer/package.json.
Configuring ng-packagr in "package.json" is deprecated. Use "ng-package.json" instead.

------------------------------------------------------------------------------
Building entry point 'ngx-json-viewer'
------------------------------------------------------------------------------
⠋ Compiling with Angular sources in Ivy partial compilation mode.Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Generating FESM2020
✔ Generating FESM2015
✔ Copying assets
ℹ Removing scripts section in package.json as it's considered a potential security vulnerability.
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built ngx-json-viewer

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/m/workspace/ngx-json-viewer
 - to:   /Users/m/workspace/ngx-json-viewer/dist
------------------------------------------------------------------------------

Build at: 2022-04-06T23:56:59.957Z - Time: 1707ms

✨  Done in 2.76s.
```

**Comment by micahstubbs** [comment]
A few things to fix. Let's try to fix them one by one.

**Comment by micahstubbs** [comment]
```bash
npx browserslist@latest --update-db

Latest version:     1.0.30001325
Installed versions: 1.0.30001204, 1.0.30001325
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ yarn add -W caniuse-lite
warning Pattern ["caniuse-lite@^1.0.30001325"] is trying to unpack in the same destination "Library/Caches/Yarn/v6/npm-caniuse-lite-1.0.30001325-2b4ad19b77aa36f61f2eaf72e636d7481d55e606-integrity/node_modules/caniuse-lite" as pattern ["caniuse-lite@^1.0.30001317","caniuse-lite@^1.0.30001181","caniuse-lite@^1.0.30001317"]. This could result in non-deterministic behavior, skipping.
warning " > ng-packagr@13.3.0" has incorrect peer dependency "tslib@^2.3.0".
warning "ng-packagr > postcss-preset-env@7.4.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-color-function@1.1.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-font-format-keywords@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-hwb-function@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-ic-unit@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-is-pseudo-class@2.0.2" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-normalize-display-values@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-oklab-function@1.1.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-progressive-custom-properties@1.3.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > css-blank-pseudo@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > css-has-pseudo@3.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > css-prefers-color-scheme@6.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-clamp@4.1.0" has incorrect peer dependency "postcss@^8.4.6".
warning "ng-packagr > postcss-preset-env > postcss-color-functional-notation@4.2.2" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-color-hex-alpha@8.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-color-rebeccapurple@7.0.2" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > postcss-custom-properties@12.1.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-dir-pseudo-class@6.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-double-position-gradients@3.1.1" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-env-function@4.0.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-focus-visible@6.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-focus-within@5.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-gap-properties@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-image-set-function@4.0.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-lab-function@4.2.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-logical@5.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-nesting@10.1.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-overflow-shorthand@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-place@7.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-pseudo-class-any-link@7.1.2" has incorrect peer dependency "postcss@^8.4".
Cleaning package.json dependencies from caniuse-lite
$ yarn remove -W caniuse-lite
warning " > ng-packagr@13.3.0" has incorrect peer dependency "tslib@^2.3.0".
warning "ng-packagr > postcss-preset-env@7.4.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-color-function@1.1.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-font-format-keywords@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-hwb-function@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-ic-unit@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-is-pseudo-class@2.0.2" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-normalize-display-values@1.0.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-oklab-function@1.1.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > @csstools/postcss-progressive-custom-properties@1.3.0" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > css-blank-pseudo@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > css-has-pseudo@3.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > css-prefers-color-scheme@6.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-clamp@4.1.0" has incorrect peer dependency "postcss@^8.4.6".
warning "ng-packagr > postcss-preset-env > postcss-color-functional-notation@4.2.2" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-color-hex-alpha@8.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-color-rebeccapurple@7.0.2" has incorrect peer dependency "postcss@^8.3".
warning "ng-packagr > postcss-preset-env > postcss-custom-properties@12.1.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-dir-pseudo-class@6.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-double-position-gradients@3.1.1" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-env-function@4.0.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-focus-visible@6.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-focus-within@5.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-gap-properties@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-image-set-function@4.0.6" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-lab-function@4.2.0" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-logical@5.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-nesting@10.1.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-overflow-shorthand@3.0.3" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-place@7.0.4" has incorrect peer dependency "postcss@^8.4".
warning "ng-packagr > postcss-preset-env > postcss-pseudo-class-any-link@7.1.2" has incorrect peer dependency "postcss@^8.4".
caniuse-lite has been successfully updated

No target browser changes # #

**Comment by micahstubbs** [comment]
Now, let's fix this:

```bash
WARNING: Found configuration in /Users/m/workspace/ngx-json-viewer/package.json.
Configuring ng-packagr in "package.json" is deprecated. Use "ng-package.json" instead
```

**Comment by micahstubbs** [comment]
fixed! I added this `ng-package.json`:

```json
{
  "lib": {
    "entryFile": "index.ts"
  }
}
```

**Comment by micahstubbs** [comment]
Now, let's test to see if `yarn start` works.

**Comment by micahstubbs** [comment]
Here is the first error that we see from `yarn start`:

```bash
Error: node_modules/ngx-json-viewer/src/ngx-json-viewer/ngx-json-viewer.component.d.ts:22:21 - error TS2694: Namespace '"/Users/m/workspace/ngx-json-viewer/example/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

22     static ɵfac: i0.ɵɵFactoryDeclaration<NgxJsonViewerComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
```

**Comment by micahstubbs** [comment]
I also see this error: 

```bash
Error: ./node_modules/ngx-json-viewer/fesm2015/ngx-json-viewer.mjs 
146:184-196
Can't import the named export 'CommonModule' 
from non EcmaScript module 
(only default export is available)
```

**Comment by micahstubbs** [comment]
ah! It looks like I need to upgrade the example project to Angular13 too. 💡 

Let's try that.

**Comment by micahstubbs** [comment]
```bash
npx @angular/cli@12 update @angular/core@12 @angular/cli@12
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 29 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "12.2.17" (was "0.1100.6")...
    Updating package.json with dependency @angular/cli @ "12.2.17" (was "11.0.6")...
    Updating package.json with dependency @angular/compiler-cli @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency karma @ "6.3.17" (was "5.1.1")...
    Updating package.json with dependency typescript @ "4.3.5" (was "4.0.5")...
    Updating package.json with dependency @angular/animations @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/common @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/compiler @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/core @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/forms @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/platform-browser @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency @angular/router @ "12.2.16" (was "11.0.7")...
    Updating package.json with dependency zone.js @ "0.11.5" (was "0.10.3")...
  UPDATE package.json (1240 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

❯ Remove deprecated options from 'angular.json' that are no longer present in v12.
  UPDATE angular.json (3763 bytes)
  Migration completed.

❯ Update 'zone.js' to version 0.11.x.
  Read more about this here: https://github.com/angular/angular/blob/master/packages/zone.js/CHANGELOG.md#breaking-changes-since-zonejs-v0111
  UPDATE package.json (1240 bytes)
  UPDATE src/polyfills.ts (2816 bytes)
  UPDATE src/test.ts (743 bytes)
  UPDATE src/environments/environment.ts (665 bytes)
✔ Packages installed successfully.
  Migration completed.

❯ Remove 'emitDecoratorMetadata' TypeScript compiler option.
  Decorator metadata is no longer needed by Angular.
  Read more about this here: https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
  Migration completed.

❯ Lazy loading syntax migration.
  Update lazy loading string syntax to use dynamic imports.
  Migration completed.

❯ Remove deprecated ViewEngine-based i18n build and extract options.
  Options present in the configuration will be converted to use non-deprecated options.
  Migration completed.

❯ Updates Web Worker consumer usage to use the new syntax supported directly by Webpack 5.
  Migration completed.

❯ Remove invalid 'skipTests' option in '@schematics/angular:module' Angular schematic options.
  Migration completed.

❯ Replace the deprecated '--prod' in package.json scripts.
  UPDATE package.json (1240 bytes)
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ Removes `canActivate` from a `Route` config when `redirectTo` is also present.
  Migration completed.

❯ In Angular version 12, the type of ActivatedRouteSnapshot.fragment is nullable.
  This migration automatically adds non-null assertions to it.
  Migration completed.

❯ `XhrFactory` has been moved from `@angular/common/http` to `@angular/common`.
  Migration completed.

❯ Automatically migrates shadow-piercing selector from `/deep/` to the recommended alternative `::ng-deep`.
  Migration completed.
```

**Comment by micahstubbs** [comment]
It looks like the update from Angular11 to Angular12 worked. Now let's see if we can do the 12 --> 13 upgrade for the examples.

**Comment by micahstubbs** [comment]
```bash
cd examples
npx @angular/cli@13 update @angular/core@13 @angular/cli@13

The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 13.3.2 to perform the update.
✔ Package successfully installed.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 29 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.3.2" (was "12.2.17")...
    Updating package.json with dependency @angular/cli @ "13.3.2" (was "12.2.17")...
    Updating package.json with dependency @angular/compiler-cli @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency typescript @ "4.6.3" (was "4.3.5")...
    Updating package.json with dependency @angular/animations @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/common @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/compiler @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/core @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/forms @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/platform-browser @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.3.2" (was "12.2.16")...
    Updating package.json with dependency @angular/router @ "13.3.2" (was "12.2.16")...
  UPDATE package.json (1229 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

❯ Remove polyfills required only for Internet Explorer which is no longer supported.
  UPDATE src/polyfills.ts (2340 bytes)
  Migration completed.

❯ Remove no longer valid Angular schematic options from `angular.json`.
  Migration completed.

❯ Remove deprecated options from 'angular.json' that are no longer present in v13.
  UPDATE angular.json (3418 bytes)
  Migration completed.

❯ Updating '.gitignore' to include '.angular/cache'.
  UPDATE .gitignore (647 bytes)
  Migration completed.

❯ Update library projects to be published in partial mode and removed deprecated options from ng-packagr configuration.
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ Migrates `[routerLink]=""` in templates to `[routerLink]="[]"` because these links are likely intended to route to the current page with updated fragment/query params.
  Migration completed.

❯ In Angular version 13, the `teardown` flag in `TestBed` will be enabled by default.
  This migration automatically opts out existing apps from the new teardown behavior.
  UPDATE src/test.ts (790 bytes)
  Migration completed.

❯ As of Angular version 13, `entryComponents` are no longer necessary.
  Migration completed.
  ```

**Comment by micahstubbs** [comment]
Now, let's try `yarn start` again 🤞 

```bash
yarn start
yarn run v1.22.18
$ yarn build && yarn --cwd ./example add ../dist && yarn --cwd ./example start
$ ng-packagr -p ng-package.json
Building Angular Package
(node:6405) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/m/workspace/ngx-json-viewer/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

------------------------------------------------------------------------------
Building entry point 'ngx-json-viewer'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
ℹ Removing scripts section in package.json as it's considered a potential security vulnerability.
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built ngx-json-viewer

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/m/workspace/ngx-json-viewer
 - to:   /Users/m/workspace/ngx-json-viewer/dist
------------------------------------------------------------------------------

Build at: 2022-04-07T01:20:27.537Z - Time: 1496ms

[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > codelyzer@6.0.1" has incorrect peer dependency "@angular/compiler@>=2.3.1 <12.0.0 || ^11.0.0-next || ^11.1.0-next || ^11.2.0-next".
warning " > codelyzer@6.0.1" has incorrect peer dependency "@angular/core@>=2.3.1 <12.0.0 || ^11.0.0-next || ^11.1.0-next || ^11.2.0-next".
[4/4] 🔨  Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ ngx-json-viewer@3.0.2
info All dependencies
└─ ngx-json-viewer@3.0.2
$ ng serve
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   1.70 MB |
polyfills.js          | polyfills     | 294.79 kB |
styles.css, styles.js | styles        | 173.22 kB |
main.js               | main          |   7.76 kB |
runtime.js            | runtime       |   6.51 kB |

                      | Initial Total |   2.17 MB

Build at: 2022-04-07T01:20:34.754Z - Hash: 9baa221ddf554841 - Time: 2930ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
```

**Comment by micahstubbs** [comment]
Here's what I see at http://localhost:4200/

Looks good!
![Screen Shot 2022-04-06 at 6 22 36 PM](https://user-images.githubusercontent.com/2119400/162101372-db6e4d61-8d3e-4e99-b21f-8c4743e9ee87.png)

**Comment by micahstubbs** [comment]
Now, let's run the tests for the example. It looks like there are 0 tests, and 1 TypeScript error. I'm not sure if we need to fix the TypeScript error now.

```bash
cd example
yarn test

yarn test
yarn run v1.22.18
$ ng test
✔ Browser application bundle generation complete.

Error: src/app/app.component.spec.ts:22:16 - error TS2339: Property 'title' does not exist on type 'AppComponent'.

22     expect(app.title).toEqual('example');
                  ~~~~~



06 04 2022 18:23:38.008:WARN [karma]: No captured browser, open http://localhost:9876/
06 04 2022 18:23:38.150:INFO [karma-server]: Karma v6.3.17 server started at http://localhost:9876/
06 04 2022 18:23:38.150:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
06 04 2022 18:23:38.154:INFO [launcher]: Starting browser Chrome
06 04 2022 18:23:44.302:INFO [Chrome 100.0.4896.75 (Mac OS 10.15.7)]: Connected on socket 2a3C8sel-slT0rz2AAAB with id 81111516
06 04 2022 18:23:44.396:WARN [web-server]: 404: /_karma_webpack_/main.js
Chrome 100.0.4896.75 (Mac OS 10.15.7): Executed 0 of 0 SUCCESS (0.012 secs / 0 secs)
TOTAL: 0 SUCCESS
```

**Comment by micahstubbs** [comment]
Let's run `yarn e2e` and see what happens. 

```bash
yarn e2e

yarn run v1.22.18
$ ng e2e
Protractor has been deprecated including its support in the Angular CLI. For additional information and alternatives, please see https://github.com/angular/protractor/issues/5502.
```

**Comment by micahstubbs** [comment]
In any case, I am unable to run the `yarn e2e` tests with this error:

```bash
yarn e2e
yarn run v1.22.18
$ ng e2e
Protractor has been deprecated including its support in the Angular CLI. For additional information and alternatives, please see https://github.com/angular/protractor/issues/5502.

[18:32:33] E/downloader - options.uri is a required argument
[18:32:33] I/update - chromedriver: file exists /ngx-json-viewer/example/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_100.0.4896.60.zip
[18:32:33] I/update - chromedriver: unzipping chromedriver_100.0.4896.60.zip
An unhandled exception occurred: Invalid filename: /ngx-json-viewer/example/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_100.0.4896.60.zip
See "/private/var/folders/br/td1k_9791514kg2gpt026v0m0000gn/T/ng-4LpNBp/angular-errors.log" for further details.
error Command failed with exit code 127.
```

the contents of `angular-errors.log` are:

```bash
[error] Error: Invalid filename: /ngx-json-viewer/example/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_100.0.4896.60.zip
    at unzip (/ngx-json-viewer/example/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:232:19)
    at /ngx-json-viewer/example/node_modules/protractor/node_modules/webdriver-manager/built/lib/cmds/update.js:205:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async execute (/ngx-json-viewer/example/node_modules/@angular-devkit/build-angular/src/builders/protractor/index.js:99:9)
```

**Comment by micahstubbs** [comment]
I'll leave this error as it is for now and see if the PR will pass the tests in CI. 

Let's go back to the project root and run `yarn build` again, and make sure that still works.  Hooray, it does.  It appears that we now build an Ivy distribution. I think. 

Is that what this means?

> Compiling with Angular sources in Ivy partial compilation mode.

```bash
yarn build
yarn run v1.22.18
$ ng-packagr -p ng-package.json
Building Angular Package
(node:8415) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/m/workspace/ngx-json-viewer/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

------------------------------------------------------------------------------
Building entry point 'ngx-json-viewer'
------------------------------------------------------------------------------
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
ℹ Removing scripts section in package.json as it's considered a potential security vulnerability.
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built ngx-json-viewer

------------------------------------------------------------------------------
Built Angular Package
 - from: /Users/m/workspace/ngx-json-viewer
 - to:   /Users/m/workspace/ngx-json-viewer/dist
------------------------------------------------------------------------------

Build at: 2022-04-07T01:35:31.539Z - Time: 1328ms

✨  Done in 2.10s.
```
